# Operating on Data in Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
rng=np.random.default_rng(30)
ser=pd.Series(rng.integers(0,10,4))
ser

0    1
1    2
2    7
3    4
dtype: int64

In [3]:
df=pd.DataFrame(rng.integers(0,10,(3,4)),columns=['a','b','c','d'])
df

   a  b  c  d
0  3  0  6  5
1  2  7  1  8
2  0  3  7  1

In [4]:
np.exp(ser)

0       2.718282
1       7.389056
2    1096.633158
3      54.598150
dtype: float64

In [5]:
ser

0    1
1    2
2    7
3    4
dtype: int64

In [6]:
np.sin(df*np.pi /4)

          a         b         c             d
0  0.707107  0.000000 -1.000000 -7.071068e-01
1  1.000000 -0.707107  0.707107 -2.449294e-16
2  0.000000  0.707107 -0.707107  7.071068e-01

In [7]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
 'California': 423967}, name='area')
population = pd.Series({'California': 39538223, 'Texas': 29145505,
 'Florida': 21538187}, name='population')

print(population,'\n')
print(area,'\n')
print(population / area)

California    39538223
Texas         29145505
Florida       21538187
Name: population, dtype: int64

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

Alaska              NaN
California    93.257784
Florida             NaN
Texas         41.896072
dtype: float64

In [8]:
area.index

Index(['Alaska', 'Texas', 'California'], dtype='object')

In [9]:
area.index.union(population.index)

Index(['Alaska', 'California', 'Florida', 'Texas'], dtype='object')

In [10]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])

print(A,'\n')
print(B)
A + B

0    2
1    4
2    6
dtype: int64

1    1
2    3
3    5
dtype: int64

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [11]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [12]:
A = pd.DataFrame(rng.integers(0,20,(2,3)), columns=['a','b','c'])
A

    a  b   c
0   3  7  14
1  11  3   5

In [13]:
B = pd.DataFrame(rng.integers(0,20,(3,4)),columns=['a','b','c','d'])
B

    a   b   c   d
0   5  12  14  18
1  12   7   5   9
2   8  15  14  12

In [14]:
A + B

      a     b     c   d
0   8.0  19.0  28.0 NaN
1  23.0  10.0  10.0 NaN
2   NaN   NaN   NaN NaN

In [15]:
A.add(B)

      a     b     c   d
0   8.0  19.0  28.0 NaN
1  23.0  10.0  10.0 NaN
2   NaN   NaN   NaN NaN

In [16]:
A.add(B, fill_value=A.values.mean())

           a          b          c          d
0   8.000000  19.000000  28.000000  25.166667
1  23.000000  10.000000  10.000000  16.166667
2  15.166667  22.166667  21.166667  19.166667

In [19]:
A = rng.integers(20, size=(3,4))
A

array([[ 8,  6,  4,  3],
       [14,  7,  4,  9],
       [13,  5,  0,  6]])

In [21]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 6,  1,  0,  6],
       [ 5, -1, -4,  3]])

In [23]:
df = pd.DataFrame(A, columns=['Q', 'R', 'S', 'T'])

df

    Q  R  S  T
0   8  6  4  3
1  14  7  4  9
2  13  5  0  6

In [25]:
df.iloc[0]

Q    8
R    6
S    4
T    3
Name: 0, dtype: int64

In [26]:
df.loc[0]

Q    8
R    6
S    4
T    3
Name: 0, dtype: int64

In [30]:
df.subtract(df['R'], axis=0)

   Q  R  S  T
0  2  0 -2 -3
1  7  0 -3  2
2  8  0 -5  1