In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import sys

In [62]:
df = sns.load_dataset("tips")

In [63]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [65]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [66]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [67]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [68]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [69]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [70]:
X = df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
y = df['total_bill']

In [71]:
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size=0.2, random_state=42)

In [72]:
x_train.head()

      tip   sex smoker   day    time  size
228  2.72  Male     No   Sat  Dinner     2
208  2.03  Male    Yes   Sat  Dinner     2
96   4.00  Male    Yes   Fri  Dinner     2
167  4.50  Male     No   Sun  Dinner     4
84   2.03  Male     No  Thur   Lunch     2

In [73]:
le1 = sklearn.preprocessing.LabelEncoder()
le2 = sklearn.preprocessing.LabelEncoder()
le3 = sklearn.preprocessing.LabelEncoder()

In [74]:
x_train['sex'] = le1.fit_transform(x_train['sex'])
x_train['smoker'] = le2.fit_transform(x_train['smoker'])
x_train['time'] = le3.fit_transform(x_train['time'])

In [75]:
x_train.head()

      tip  sex  smoker   day  time  size
228  2.72    1       0   Sat     0     2
208  2.03    1       1   Sat     0     2
96   4.00    1       1   Fri     0     2
167  4.50    1       0   Sun     0     4
84   2.03    1       0  Thur     1     2

In [76]:
x_test['sex'] = le1.transform(x_test['sex'])
x_test['smoker'] = le2.transform(x_test['smoker'])
x_test['time'] = le3.transform(x_test['time'])

In [77]:
ct = sklearn.compose.ColumnTransformer(transformers=[('onehot', sklearn.preprocessing.OneHotEncoder(drop='first'), [3])], remainder='passthrough')

In [78]:
x_train = ct.fit_transform(x_train)

In [79]:
x_test = ct.transform(x_test)

In [80]:
svr = sklearn.svm.SVR()

In [81]:
svr.fit(x_train, y_train)

SVR()

In [82]:
y_pred = svr.predict(x_test)

In [83]:
sklearn.metrics.r2_score(y_test, y_pred)

0.5502250005312896