In [8]:
import numpy as np
import pandas as pd

In [9]:
matrix = [[80,-5,60],[78,-3,62],[82,-6,65],[81,-4,68]]

matrix

[[80, -5, 60], [78, -3, 62], [82, -6, 65], [81, -4, 68]]

In [10]:
df = pd.DataFrame(matrix,columns=['N1','N2','N3'], index=['A1','A2','A3','A4'])
df

    N1  N2  N3
A1  80  -5  60
A2  78  -3  62
A3  82  -6  65
A4  81  -4  68

In [11]:
maxi_max = []
maxi_min = []
equally_likely = []
hurwicz = []
minimax_regret = []
max_num = []

alpha = 0.3

for i in matrix :
    maxi_max.append(max(i))
    maxi_min.append(min(i))
    equally_likely.append(sum(i)/len(i))
    hurwicz.append((alpha*max(i))+((1 - alpha)*min(i)))

for i in df.columns:
    max_num.append(max(df[i]))

regret_matrix = [[max_num[j] - matrix[i][j] for j in range(len(matrix[i]))] for i in range(len(matrix))]

for i in regret_matrix:
    minimax_regret.append(max(i))

df['maxi_max'] = maxi_max
df['maxi_min'] = maxi_min
df['equally_likely'] = equally_likely
df['hurwicz'] = hurwicz
df['minimax_regret'] = minimax_regret

df.loc['Result'] = [None] * df.shape[1]
df

C:\Users\ASUS\AppData\Local\Temp\ipykernel_3648\2763725148.py:30: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df.loc['Result'] = [None] * df.shape[1]

,N1,N2,N3,maxi_max,maxi_min,equally_likely,hurwicz,minimax_regret
A1,80,-5,60,80,-5,45.000000,20.5,8
A2,78,-3,62,78,-3,45.666667,21.3,6
A3,82,-6,65,82,-6,47.000000,20.4,3
A4,81,-4,68,81,-4,48.333333,21.5,1
Result,None,None,None,None,None,NaN,NaN,None

In [12]:
print(f"maxi_max --> A{df.index[df['maxi_max'] == max(df['maxi_max'])]}")
print(f"maxi_min --> A{df.index[df['maxi_min'] == max(df['maxi_min'])]}")
print(f"equally_likely --> A{df.index[df['equally_likely'] == max(df['equally_likely'])]}")
print(f"hurwicz --> A{df.index[df['hurwicz'] == max(df['hurwicz'])]}")
print(f"minimax_regret --> A{df.index[df['minimax_regret'] == min(df['minimax_regret'])]}")

TypeError: '>' not supported between instances of 'NoneType' and 'int'